// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/indexer.proto

package indexer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IndexRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexRequest) Reset()         { *m = IndexRequest{} }
func (m *IndexRequest) String() string { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()    {}
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0899a86e4ced20, []int{0}
}

func (m *IndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexRequest.Unmarshal(m, b)
}
func (m *IndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexRequest.Marshal(b, m, deterministic)
}
func (m *IndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexRequest.Merge(m, src)
}
func (m *IndexRequest) XXX_Size() int {
	return xxx_messageInfo_IndexRequest.Size(m)
}
func (m *IndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexRequest proto.InternalMessageInfo

func (m *IndexRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type IndexResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexResponse) Reset()         { *m = IndexResponse{} }
func (m *IndexResponse) String() string { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()    {}
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0899a86e4ced20, []int{1}
}

func (m *IndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResponse.Unmarshal(m, b)
}
func (m *IndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResponse.Marshal(b, m, deterministic)
}
func (m *IndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResponse.Merge(m, src)
}
func (m *IndexResponse) XXX_Size() int {
	return xxx_messageInfo_IndexResponse.Size(m)
}
func (m *IndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResponse proto.InternalMessageInfo

func (m *IndexResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type SearchRequest struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0899a86e4ced20, []int{2}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

type SearchResponse struct {
	Pages                []*SearchResponse_Page `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0899a86e4ced20, []int{3}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetPages() []*SearchResponse_Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

type SearchResponse_Page struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse_Page) Reset()         { *m = SearchResponse_Page{} }
func (m *SearchResponse_Page) String() string { return proto.CompactTextString(m) }
func (*SearchResponse_Page) ProtoMessage()    {}
func (*SearchResponse_Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0899a86e4ced20, []int{3, 0}
}

func (m *SearchResponse_Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse_Page.Unmarshal(m, b)
}
func (m *SearchResponse_Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse_Page.Marshal(b, m, deterministic)
}
func (m *SearchResponse_Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse_Page.Merge(m, src)
}
func (m *SearchResponse_Page) XXX_Size() int {
	return xxx_messageInfo_SearchResponse_Page.Size(m)
}
func (m *SearchResponse_Page) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse_Page.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse_Page proto.InternalMessageInfo

func (m *SearchResponse_Page) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SearchResponse_Page) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchResponse_Page) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*IndexRequest)(nil), "IndexRequest")
	proto.RegisterType((*IndexResponse)(nil), "IndexResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*SearchResponse_Page)(nil), "SearchResponse.Page")
}

func init() { proto.RegisterFile("api/indexer.proto", fileDescriptor_7c0899a86e4ced20) }

var fileDescriptor_7c0899a86e4ced20 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x37, 0xb6, 0x5d, 0xf1, 0xe9, 0x56, 0x7d, 0xec, 0xa1, 0xf4, 0x54, 0xe2, 0xa5, 0x28,
	0x44, 0x58, 0xff, 0x82, 0x97, 0xbd, 0x49, 0xfd, 0x03, 0x66, 0xb7, 0x8f, 0xb5, 0xb0, 0x34, 0x31,
	0x49, 0x51, 0xaf, 0xfe, 0x72, 0x49, 0xd2, 0x82, 0x75, 0x6f, 0x33, 0x93, 0x8f, 0x30, 0x6f, 0xe0,
	0x56, 0xea, 0xee, 0xb1, 0xeb, 0x5b, 0xfa, 0x22, 0x23, 0xb4, 0x51, 0x4e, 0xf1, 0x0a, 0xae, 0xb6,
	0x3e, 0x68, 0xe8, 0x63, 0x20, 0xeb, 0xf0, 0x06, 0x92, 0xc1, 0x1c, 0x0b, 0x56, 0xb1, 0xfa, 0xa2,
	0xf1, 0x92, 0xdf, 0xc1, 0x6a, 0x24, 0xac, 0x56, 0xbd, 0x25, 0x44, 0x48, 0x77, 0xaa, 0xfd, 0x1e,
	0x99, 0xa0, 0x3d, 0xf4, 0x4a, 0xd2, 0xec, 0xdf, 0xa7, 0x7f, 0x10, 0xd2, 0x4f, 0x65, 0xda, 0x09,
	0xf2, 0x9a, 0xff, 0x30, 0xc8, 0x27, 0x6a, 0xfc, 0xeb, 0x1e, 0x32, 0x2d, 0x0f, 0x64, 0x0b, 0x56,
	0x25, 0xf5, 0xe5, 0x66, 0x2d, 0xe6, 0xef, 0xe2, 0x45, 0x1e, 0xa8, 0x89, 0x48, 0xf9, 0x0c, 0xa9,
	0xb7, 0xa7, 0x15, 0x71, 0x0d, 0x99, 0xeb, 0xdc, 0x91, 0x8a, 0xb3, 0x90, 0x45, 0xe3, 0xd3, 0xbd,
	0x1a, 0x7a, 0x57, 0x24, 0x15, 0xab, 0x93, 0x26, 0x9a, 0xcd, 0x1b, 0x9c, 0x6f, 0xe3, 0x02, 0x58,
	0x43, 0x16, 0x24, 0xae, 0xc4, 0xdf, 0x0d, 0xca, 0x5c, 0xcc, 0x0e, 0xe6, 0x0b, 0x7c, 0x80, 0x65,
	0x2c, 0x86, 0xb9, 0x98, 0xdd, 0x59, 0x5e, 0xff, 0x6b, 0xcc, 0x17, 0xbb, 0x65, 0x58, 0xf6, 0xe9,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x03, 0xac, 0x94, 0xf7, 0x6e, 0x01, 0x00, 0x00,
}
